### ISSUE TITLE
Model/BasicPaymentErrors : is_not_possible_data

### ISSUE THREAD

**Issue by shilpapatel-bcs** [click-llc/click-integration-php#6]
Model/BasicPaymentErrors : is_not_possible_data

function is 
private function is_not_possible_data($request){
        if(!(
            isset($request['click_trans_id']) &&
            isset($request['service_id']) &&
            isset($request['merchant_trans_id']) &&
            isset($request['merchant_prepare_id']) &&
            isset($request['amount']) &&
            isset($request['action']) &&
            isset($request['error']) &&
            isset($request['error_note']) &&
            isset($request['sign_time']) &&
            isset($request['sign_string']) &&
            isset($request['click_paydoc_id'])
        ) || ((int)$request['action'] > 0 && !isset($request['merchant_prepare_id']))){
            return true;
        }
        return false;
    }
I think we dont need ' isset($request['merchant_prepare_id']) && '  condition here, as I already had problem with it

**Comment by tensor2flow** [comment]
I fixed this bug
